language: python
python:
  - 2.7
  - 3.6  
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install future pyttk; fi
  - pip install numpy matplotlib numexpr xlrd pandas
  - python setup.py install
script:
    python -m pandastable.tests

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
